### ISSUE TITLE
Build 32-bit for gcc 4.8

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#351]
It would be nice for the gcc 4.8 Travis target to build for the 32-bit address model

**Comment by brunocodutra** [comment]
I've never set up travis to cross-compile to 32-bit, so I'm afraid I can't help you much, but what happens if you install gcc-multilib in addition to gcc?

**Comment by vinniefalco** [comment]
It screws up. I'm not exactly sure how to specify it, how does this look?
```
    # older GCC, 32-bit release
    - compiler: gcc
      env:
        - GCC_VER=4.8
        - VARIANT=release
        - ADDRESS_MODEL=32
      addons:
        apt:
          packages:
            - gcc-4.8
            - gcc-multilib
            - g++-4.8
            - *base_packages
          sources:
            - *base_sources
```
